#!/usr/bin/env racket
#lang ricoeur/secondary-lit/preprocessor

(topic-model
 [History 0.01976 (history philosophy truth work time explanation event)]
 [Evil 0.00881 (evil myth sin man theology world experience)]
 [Testimony 0.00766 (testimony freedom meaning witness hope consciousness time)]
 [Project 0.00655 (choice attention freedom act project consciousness decision)]
 [Language 0.00444 (language text translation work time word meaning)]
 [Memory 0.01069 (memory die time history representation past work)]
 [Ideology 0.0046 (concept labor ideology alienation production man relation)]
 [Consciousness 0.00672 (consciousness world meaning reduction phenomenology)]
 [Interpretation 0.01137 (critique experience text interpretation understanding tradition ideology)]
 [Phenomenology 0.0161 (phenomenology sense consciousness ego world experience body)]
 [Death 0.0059 (death time life work memory narrator relation)]
 [|Language Theory| 0.00658 (language theory philosophy system science problem question)]
 [Violence 0.00805 (man history power work world violence word)]
 [Body 0.00849 (body action movement effort object world consciousness)]
 [Substance 0.0069 (substance philosophy problem soul science form question)]
 [Discourse 0.01174 (discourse text meaning world work language reference)]
 [Psychoanalysis 0.01108 (psychoanalysis theory meaning work language interpretation point)]
 [Pleasure 0.00613 (pleasure pain life imagination object body feeling)]
 [Decision 0.00577 (project decision consciousness action description relation possibility)]
 [Meaning 0.01291 (meaning interpretation symbol reflection language symbolism consciousness)]
 [Involuntary 0.00448 (emotion habit body consciousness desire movement action)]
 [Action 0.01746 (action sense question identity character relation person)]
 [Freedom 0.00513 (freedom death consciousness consent necessity man experience)]
 [Imagination 0.00707 (image world fiction imagination sense meaning language)]
 [Utopia 0.00353 (utopia language sense imagination action ideology world)]
 [Finitude 0.01086 (man reflection thing point idea synthesis finitude)]
 [Dream 0.00406 (dream work philosophy experience point interpretation man)]
 [Revelation 0.00907 (text discourse revelation sense world language faith)]
 [Metaphor 0.00801 (metaphor level meaning language word discourse sense)]
 [Justice 0.01306 (justice idea law sense state fact order)]
 [Text 0.0166 (text interpretation language explanation discourse world relation)]
 [Time 0.01411 (time work text story reader history fiction)])
