image:
- Visual Studio 2015
- Ubuntu1604

environment:
  matrix:
    - RACKET_VERSION: 7.0
      WINDOWS_TAR: https://download.racket-lang.org/releases/7.0/installers/racket-minimal-7.0-x86_64-win32.tgz
    - RACKET_VERSION: HEAD
      WINDOWS_TAR: https://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-win32.tgz

for:
  -
    matrix:
      only:
        - image: Ubuntu1604
    environment:
      RACKET_DIR: /home/appveyor/racket
    install:
      - git clone https://github.com/greghendershott/travis-racket.git
      - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
      - export PATH="${RACKET_DIR}/bin:${PATH}"
    build_script:
      - '"${RACKET_DIR}/bin/raco" pkg install --auto --name ricoeur-tei-utils'
    test_script:
      - '"${RACKET_DIR}/bin/raco" test -x -p ricoeur-tei-utils'
      - '"${RACKET_DIR}/bin/raco" setup --check-pkg-deps ricoeur'

  -
    matrix:
      only:
        - image: Visual Studio 2015
    install:
      - curl -o C:\racket.tgz --location %WINDOWS_TAR%
      - ps: 7z x -so C:\racket.tgz | 7z x -si -ttar -o"C:\"
      - dir C:\racket
      - echo "Minimal Racket: Installing packages for raco test..."
      - C:\racket\raco.exe pkg install --auto -i rackunit-lib compiler-lib
    build_script:
      - C:\racket\raco.exe pkg install --auto --name ricoeur-tei-utils
    test_script:
      - C:\racket\raco.exe test -x -p ricoeur-tei-utils
      - C:\racket\raco.exe setup --check-pkg-deps ricoeur


