image:
- Ubuntu1604
- Visual Studio 2015

environment:
  matrix:
    - RACKET_VERSION: 7.0
    - RACKET_VERSION: HEAD

for:
  -
    matrix:
      only:
        - image: Ubuntu1604
    environment:
      RACKET_DIR: ~/../racket
    install:
      - pwd
      - echo ~
      - git clone https://github.com/greghendershott/travis-racket.git
      - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
      - export PATH="${RACKET_DIR}/bin:${PATH}"
    build_script:
      - '"${RACKET_DIR}/bin/raco" pkg install --auto --name ricoeur-tei-utils'
    test_script:
      - '"${RACKET_DIR}/bin/raco" test -x -p ricoeur-tei-utils'
      - '"${RACKET_DIR}/bin/raco" setup --check-pkg-deps ricoeur'

  -
    matrix:
      only:
        - image: Visual Studio 2015
    install:
      - cmd: echo Windows install is a noop.
    build_script:
      - cmd: echo Windows build_script is a noop.
    test_script:
      - cmd: echo Windows test_script is a noop.


