image:
- Visual Studio 2015

environment:
  matrix:
    - RACKET_VERSION: 7.1
      WINDOWS_TAR: https://download.racket-lang.org/releases/7.1/installers/racket-minimal-7.1-x86_64-win32.tgz
    - RACKET_VERSION: HEAD
      WINDOWS_TAR: https://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-win32.tgz

install:
  - curl -o C:\racket.tar.gz --location %WINDOWS_TAR%
  - mkdir C:\racket
  - bash -c "tar -xzf $(cygpath -u 'C:\racket.tar.gz') -C $(cygpath -u 'C:\racket') --strip-components 1"
  - echo "Minimal Racket: Installing packages for raco test..."
  - C:\racket\raco.exe pkg install --auto -i rackunit-lib compiler-lib
build_script:
  - C:\racket\raco.exe pkg install --auto --name ricoeur-tei-utils
test_script:
  - C:\racket\raco.exe test -x -p ricoeur-tei-utils
  - C:\racket\raco.exe setup --check-pkg-deps ricoeur
