language: c

# Based from: https://github.com/greghendershott/travis-racket

# Optional: Remove to use Travis CI's older infrastructure.
sudo: false

env:
  global:
    # Supply a global RACKET_DIR environment variable. This is where
    # Racket will be installed. A good idea is to use ~/racket because
    # that doesn't require sudo to install and is therefore compatible
    # with Travis CI's newer container infrastructure.
    - RACKET_DIR=~/racket
  matrix:
    # Supply at least one RACKET_VERSION environment variable. This is
    # used by the install-racket.sh script (run at before_install,
    # below) to select the version of Racket to download and install.
    #
    # Supply more than one RACKET_VERSION (as in the example below) to
    # create a Travis-CI build matrix to test against multiple Racket
    # versions.
    - RACKET_VERSION=7.4
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=HEADCS

matrix:
  allow_failures:
#   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
- "export DISPLAY=:99.0" # mbutterick says needed for `racket/gui`
- "sh -e /etc/init.d/xvfb start" # mbutterick says needed for `racket/gui`
# hack until merged into upstream
#- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
#- cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
- curl -sL https://github.com/LiberalArtist/travis-racket/raw/racketcs/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

install:
 - raco pkg install -j 4 --auto --name ricoeur-tei-utils

before_script:

# Here supply steps such as raco make, raco test, etc.  You can run
# `raco pkg install --deps search-auto` to install any required
# packages without it getting stuck on a confirmation prompt.
script:
 - raco test -x -p ricoeur-tei-utils

after_success:
 - raco setup --check-pkg-deps --pkgs ricoeur-tei-utils
 - raco pkg install --deps search-auto cover cover-coveralls
 - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
